// Generated by CoffeeScript 1.3.3
(function() {
  var JadeAngularJsCompiler, fileWriter, fs, jade, mkdirp, sysPath,
    __hasProp = {}.hasOwnProperty;

  jade = require('jade');

  sysPath = require('path');

  mkdirp = require('mkdirp');

  fs = require('fs');

  fileWriter = function(newFilePath) {
    return function(err, content) {
      var dirname;
      if (err != null) {
        throw err;
      }
      if (!(content != null)) {
        return;
      }
      dirname = sysPath.dirname(newFilePath);
      return mkdirp(dirname, '0775', function(err) {
        if (err != null) {
          throw err;
        }
        return fs.writeFile(newFilePath, content, function(err) {
          if (err != null) {
            throw err;
          }
        });
      });
    };
  };

  module.exports = JadeAngularJsCompiler = (function() {

    JadeAngularJsCompiler.prototype.brunchPlugin = true;

    JadeAngularJsCompiler.prototype.type = 'template';

    JadeAngularJsCompiler.prototype.extension = 'jade';

    function JadeAngularJsCompiler(config) {
      var _ref, _ref1, _ref10, _ref11, _ref12, _ref13, _ref2, _ref3, _ref4, _ref5, _ref6, _ref7, _ref8, _ref9;
      this["public"] = ((_ref = config.paths) != null ? _ref["public"] : void 0) || "_public";
      this.pretty = !!((_ref1 = config.plugins) != null ? (_ref2 = _ref1.jade) != null ? _ref2.pretty : void 0 : void 0);
      this.doctype = ((_ref3 = config.plugins) != null ? (_ref4 = _ref3.jade) != null ? _ref4.doctype : void 0 : void 0) || "5";
      this.locals = ((_ref5 = config.plugins) != null ? (_ref6 = _ref5.jade_angular) != null ? _ref6.locals : void 0 : void 0) || {};
      this.modulesFolder = ((_ref7 = config.plugins) != null ? (_ref8 = _ref7.jade_angular) != null ? _ref8.modules_folder : void 0 : void 0) || "templates";
      this.compileTrigger = sysPath.normalize(this["public"] + sysPath.sep + (((_ref9 = config.paths) != null ? _ref9.jadeCompileTrigger : void 0) || 'js/dontUseMe'));
      this.singleFile = !!(config != null ? (_ref10 = config.plugins) != null ? (_ref11 = _ref10.jade_angular) != null ? _ref11.single_file : void 0 : void 0 : void 0);
      this.singleFileName = sysPath.join(this["public"], (config != null ? (_ref12 = config.plugins) != null ? (_ref13 = _ref12.jade_angular) != null ? _ref13.single_file_name : void 0 : void 0 : void 0) || "js/angular_templates.js");
    }

    JadeAngularJsCompiler.prototype.compile = function(data, path, callback) {
      var content, error;
      try {
        content = jade.compile(data, {
          compileDebug: false,
          client: false,
          filename: path,
          doctype: this.doctype,
          pretty: this.pretty
        });
        return content(this.locals);
      } catch (err) {
        return error = err;
      } finally {
        callback(error, "");
      }
    };

    JadeAngularJsCompiler.prototype.preparePair = function(pair) {
      pair.path.push(pair.path.pop().slice(0, -this.extension.length) + 'html');
      return pair.path.splice(0, 1, this["public"]);
    };

    JadeAngularJsCompiler.prototype.writeStatic = function(pair) {
      var writer;
      this.preparePair(pair);
      writer = fileWriter(sysPath.join.apply(this, pair.path));
      return writer(null, pair.result);
    };

    JadeAngularJsCompiler.prototype.setupModule = function(pair) {
      var copyfolder, jsFileName, moduleFolderIndex, moduleName, modulePath, result, virtualPathGen,
        _this = this;
      this.preparePair(pair);
      pair.path.splice(1, 1, 'js');
      moduleFolderIndex = pair.path.lastIndexOf(this.modulesFolder) + 1;
      modulePath = pair.path.slice(2, moduleFolderIndex);
      if (modulePath.length === 0) {
        modulePath.push(this.modulesFolder);
      }
      moduleName = modulePath.join('.');
      jsFileName = moduleName + '.js';
      copyfolder = pair.path.slice(0, 2);
      copyfolder.push(jsFileName);
      virtualPathGen = function() {
        var virtualPath;
        virtualPath = modulePath.concat(pair.path.slice(moduleFolderIndex));
        virtualPath = "/" + (virtualPath.join('/'));
        virtualPath = virtualPath.replace("/" + _this.modulesFolder, '');
        return virtualPath;
      };
      return result = {
        moduleName: moduleName,
        modulePath: sysPath.join.apply(this, copyfolder),
        virtualPath: virtualPathGen(),
        content: pair.result
      };
    };

    JadeAngularJsCompiler.prototype.parseStringToJSArray = function(str) {
      var stringArray;
      stringArray = '[';
      str.split('\n').map(function(e, i) {
        return stringArray += "\n'" + e.replace(/'/g, "\\'") + "',";
      });
      return stringArray += "''" + '].join("\\n")';
    };

    JadeAngularJsCompiler.prototype.writeModules = function(modules) {
      var content, moduleContent, moduleName, templates, writer,
        _this = this;
      content = "";
      for (moduleName in modules) {
        if (!__hasProp.call(modules, moduleName)) continue;
        templates = modules[moduleName];
        moduleContent = "angular.module('" + moduleName + "', [])";
        templates.map(function(e, i) {
          var inlineContent;
          inlineContent = _this.parseStringToJSArray(e.content);
          return moduleContent += "\n.run(['$templateCache', function($templateCache) {\n  return $templateCache.put('" + e.virtualPath + "', " + inlineContent + ");\n}])";
        });
        moduleContent += ";";
        if (this.singleFile) {
          content += "\n" + moduleContent;
        } else {
          writer = fileWriter(templates[0].modulePath);
          writer(null, content);
        }
      }
      if (this.singleFile) {
        return writer = fileWriter(this.singleFileName);
      }
    };

    JadeAngularJsCompiler.prototype.prepareResult = function(compiled) {
      var pathes, result,
        _this = this;
      pathes = ((function() {
        var _i, _len, _results;
        _results = [];
        for (_i = 0, _len = compiled.length; _i < _len; _i++) {
          result = compiled[_i];
          if (result.path === this.compileTrigger) {
            _results.push(result.sourceFiles);
          }
        }
        return _results;
      }).call(this))[0];
      if (pathes === void 0) {
        return [];
      }
      return pathes.map(function(e, i) {
        var content, data;
        data = fs.readFileSync(e.path, 'utf8');
        content = jade.compile(data, {
          compileDebug: false,
          client: false,
          filename: e.path,
          doctype: _this.doctype,
          pretty: _this.pretty
        });
        return result = {
          path: e.path.split(sysPath.sep),
          result: content(_this.locals)
        };
      });
    };

    JadeAngularJsCompiler.prototype.onCompile = function(compiled) {
      var modules, modulesRows, pair, preResult, _i, _len;
      preResult = this.prepareResult(compiled);
      for (_i = 0, _len = preResult.length; _i < _len; _i++) {
        pair = preResult[_i];
        if (pair.path.indexOf(this.modulesFolder) === -1 && pair.path.indexOf('assets') === -1) {
          this.writeStatic(pair);
        }
      }
      modulesRows = (function() {
        var _j, _len1, _results;
        _results = [];
        for (_j = 0, _len1 = preResult.length; _j < _len1; _j++) {
          pair = preResult[_j];
          if (pair.path.indexOf(this.modulesFolder) > -1 && pair.path.indexOf('assets') === -1) {
            _results.push(this.setupModule(pair));
          }
        }
        return _results;
      }).call(this);
      modules = {};
      modulesRows.map(function(element, index) {
        if (Object.keys(modules).indexOf(element.moduleName) === -1) {
          modules[element.moduleName] = [];
        }
        return modules[element.moduleName].push(element);
      });
      return this.writeModules(modules);
    };

    return JadeAngularJsCompiler;

  })();

}).call(this);
